apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-addon-registry
  namespace: {{ include "systemDefinitionNamespace" . }}
data:
  registries: '{
  "KubeVela":{
    "name": "KubeVela",
    "helm": {
      "url": "https://addons.kubevela.net"
    }
  }
}'
